---
title: "Data Report 2"
author: "Angelina Venetto"
date: "4/12/2022"
output: html_document
---

# Load in packages

```{r setup, include=FALSE}
library(tidytuesdayR)
library(tidyverse)
library(ggrepel)    
library(ggtext)
```

# Load in data set

```{r}
spotify_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv')
```

#This is a data report for project number 2. This project is examining how dancebility effected track popularity in the year 2019. The data is from: https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md


# Cleaning the data to only include the 3 variables being examined

```{r}
spotify_clean <- spotify_songs %>%
  select(track_popularity, danceability, date = track_album_release_date, genre = playlist_genre)
```

# Filtering the data to only include 2019 data

```{r}
spotify_pop <- spotify_clean %>%
  filter(date > "2019-01-04")
```

# Create a plot of the data

```{r}
ggplot(spotify_pop) +
  aes(x = danceability,
      y = track_popularity,
      color = genre,
      fill = genre,
      ) +
  geom_point(alpha = .3) +
  geom_smooth(
    method = "lm",
    color = "orange",
              fill = "orange")

```

# Add dark theme to plot to improve readability

```{r}
library(hrbrthemes)
ggplot(spotify_pop) +
  aes(x = danceability,
      y = track_popularity,
      color = genre,
      fill = genre,
      ) +
  geom_point(alpha = .3) +
  geom_smooth(
    method = "lm",
    color = "orange",
              fill = "orange") +
  theme_modern_rc() 


```
